config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView
from ninja import NinjaAPI, ModelSchema
from productos.models import Producto, Marca, Lugar
from typing import List

class ProductosOut(ModelSchema):
    class Config:
        model = Producto
        model_fields = ['id', 'codigo', 'lugar', 'marca', 'cantidad_disponible', 'precio_unitario', 'medidas']

class MarcaOut(ModelSchema):
    class Config:
        model = Marca
        model_fields = ['id', 'nombre', 'descripcion']


class LugarOut(ModelSchema):
    class Config:
        model = Lugar
        model_fields = ['id', 'nombre', 'descripcion']


api = NinjaAPI()

@api.get("/productos", response=List[ProductosOut])
def get_all_products(request):
    qs = Producto.objects.all()
    return qs

@api.get("/lugares", response=List[LugarOut])
def get_all_places(request):
    qs = Lugar.objects.all()
    return qs

@api.get("/marcas", response=List[MarcaOut])
def get_all_brands(request):
    qs = Marca.objects.all()
    return qs



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('productos/', include('productos.urls')),
    path('ventas/', include('ventas.urls')),
    path('compras/', include('compras.urls')),
    path("api/", api.urls),
    path('', RedirectView.as_view(pattern_name='producto-list'), name='index'),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

productos/urls.py
from django.urls import path
from .views import (
    ProductoListView,
    ProductoCreateView,
    ProductoUpdateView,
    ProductoDeleteView
)

urlpatterns = [
    path('', ProductoListView.as_view(), name='producto-list'),
    path('crear/', ProductoCreateView.as_view(), name='producto-create'),
    path('editar/<int:pk>/',
         ProductoUpdateView.as_view(), name='producto-update'),
    path('eliminar/<int:pk>/',
         ProductoDeleteView.as_view(), name='producto-delete')
]

productos/models.py
from django.db import models


class Marca(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre')
    descripcion = models.TextField(
        blank=True, null=True, verbose_name='Descripción')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'


class Lugar(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre')
    descripcion = models.TextField(
        blank=True, null=True, verbose_name='Descripción')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Lugar'
        verbose_name_plural = 'Lugares'


class Producto(models.Model):
    codigo = models.CharField(
        max_length=100, unique=True, verbose_name='Código')
    lugar = models.ForeignKey(
        Lugar, related_name='productos', on_delete=models.CASCADE)
    marca = models.ForeignKey(
        Marca, related_name='productos', on_delete=models.CASCADE)
    cantidad_disponible = models.PositiveIntegerField(
        default=0, verbose_name='Cantidad Disponible')
    precio_unitario = models.DecimalField(
        default=0, max_digits=9, decimal_places=2,
        verbose_name='Precio Unitario')
    medidas = models.CharField(max_length=255, verbose_name='Medidas')

    def __str__(self):
        return self.codigo

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

productos/forms.py
from django import forms
from .models import Producto


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo', 'lugar', 'marca', 'medidas']
        labels = {
            'codigo': 'Código',
            'marca': 'Marca',
            'lugar': 'Ubicaión',
            'medidas': 'Medidas'
        }

productos/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Producto
from .forms import ProductoForm


class ProductoListView(LoginRequiredMixin, ListView):
    # login required mixin
    login_url = reverse_lazy('login')
    # list view
    model = Producto

    def get_queryset(self):
        word = self.request.GET.get('word', '')
        productos = Producto.objects.filter(
            Q(codigo__icontains=word) | Q(medidas__icontains=word) |
            Q(marca__nombre__icontains=word)).all()
        return productos


class ProductoCreateView(LoginRequiredMixin, CreateView):
    # login required mixin
    login_url = reverse_lazy('login')
    # Create View section
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('producto-list')


class ProductoUpdateView(LoginRequiredMixin, UpdateView):
    # login required mixin
    login_url = reverse_lazy('login')
    # view saection
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('producto-list')


class ProductoDeleteView(LoginRequiredMixin, DeleteView):
    # login required mixin
    login_url = reverse_lazy('login')
    # view section
    model = Producto
    success_url = reverse_lazy('producto-list')

productos/templates/productos/producto_confirm_delete.html
{% extends 'core/panel.html' %}

{% block title %}Borrar Producto {{ object.id }} {% endblock %}

{% block content-panel %}
    <div class="py-2 px-4 row">
        <form class="col-5 mt-5" method="POST">{% csrf_token %}
            <p class="fs-4">¿Esta seguro que desea eliminar el producto "{{ object }}"?</p>
            {{ form }}
            <div class="d-flex flex-row gap-2">
                <a href="{% url 'producto-list' %}" class="btn btn-secondary flex-fill">Cancelar</a>
                <button type="submit" class="btn btn-danger flex-fill">
                    Si, Eliminar
                </button>
            </div>
        </form>
    </div>
{% endblock %}

productos/templates/productos/producto_form.html
{% extends 'core/panel.html' %}
{% load formclss %}

{% block title %}{% if object %}Editar{% else %}Crear{% endif %} producto{% endblock %}

{% block content-panel %}
    <div class="row py-2 px-4">
        <div class="card col-5 mx-auto">
            <div class="card-body">
                <div class="card-title">
                    <h3>{% if object %}Editar{% else %}Crear{% endif %} Producto</h3>
                </div>
                <form action="." method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_codigo" class="form-label">{{ form.codigo.label }}</label>
                        {{ form.codigo|addclss:"form-control" }}
                    </div>
                    <div class="mb-3">
                        <label for="id_marca" class="form-label">{{ form.marca.label }}</label>
                        {{ form.marca|addclss:"form-control" }}
                    </div>
                    <div class="mb-3">
                        <label for="id_marca" class="form-label">{{ form.lugar.label }}</label>
                        {{ form.lugar|addclss:"form-control" }}
                    </div>
                    <div class="mb-3">
                        <label for="id_codigo" class="form-label">{{ form.medidas.label }}</label>
                        {{ form.medidas|addclss:"form-control" }}
                    </div>
                    <div class="d-flex flex-row gap-2">
                        {% if object %}
                            <a href="{% url 'producto-delete' object.id %}"
                               class="btn flex-fill btn-danger">Eliminar</a>
                        {% endif %}
                        <a href="{% url 'producto-list' %}" class="btn flex-fill btn-secondary">Cancelar</a>
                        <button type="submit" class="btn flex-fill btn-primary">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

productos/templates/productos/producto_list.html
{% extends 'core/panel.html' %}

{% block title %}Productos{% endblock %}

{% block content-panel %}
    <div class="py-4">
        <div class="d-flex flex-row justify-content-between mb-4">
            <a href="{% url 'producto-create' %}" class="btn btn-primary">
                Nuevo
            </a>
            <form class="d-flex flex-row gap-2" action="." method="GET">
                <input type="text" name="word" class="form-control flex-fill" value="{{ request.GET.word }}"
                       placeholder="Buscar productos" />
                <button class="btn btn-success" type="submit">Buscar</button>
            </form>
        </div>
        <div class="table-section">
            <table class="table table-bordered table-sm table-fixed">
                <thead>
                <tr class="text-center border-bottom">
                    <th scope="col">#</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Ubicación</th>
                    <th scope="col">Codigo</th>
                    <th scope="col">Medidas</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio (Bs)</th>
                    <th scope="col">Acciones</th>
                </tr>
                </thead>
                <tbody>
                {% if object_list %}
                    {% for producto in object_list %}
                        <tr class="text-center">
                            <td>{{ producto.id }}</td>
                            <td>{{ producto.marca.nombre }}</td>
                            <td>{{ producto.lugar.nombre }}</td>
                            <td>{{ producto.codigo }}</td>
                            <td>{{ producto.medidas }}</td>
                            <td>{{ producto.cantidad_disponible }}</td>
                            <td>{{ producto.precio_unitario }}</td>
                            <td>
                                <a href="{% url 'producto-update' producto.pk %}"
                                   class="btn btn-success btn-sm">Editar</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr class="text-center">
                        <td colspan="7">Sin datos disponibles
                        </td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}