compras/urls.py
from django.urls import path
from .views import (
    compras,
    agregar_producto,
    eliminar_producto,
    limpiar_carrito,
    guardar_compra,
    ProveedorListView,
    ProveedorCreateView,
    ProveedorUpdateView,
    ProveedorDeleteView
)

urlpatterns = [
    path('proveedores/', ProveedorListView.as_view(), name='proveedor-list'),
    path('proveedores/crear/', ProveedorCreateView.as_view(),
         name='proveedor-create'),
    path('proveedores/editar/<int:pk>/',
         ProveedorUpdateView.as_view(), name='proveedor-update'),
    path('proveedores/eliminar/<int:pk>/',
         ProveedorDeleteView.as_view(), name='proveedor-delete'),
    path('agregar/producto/<int:pk>', agregar_producto,
         name='compras-add-producto'),
    path('eliminar/producto/<int:pk>',
         eliminar_producto, name='compras-del-producto'),
    path('limpiar/carrito/', limpiar_carrito, name='compras-clean'),
    path('guardar/compra/', guardar_compra, name='compras-save'),
    path('', compras, name='compras')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView
from ninja import NinjaAPI, ModelSchema
from productos.models import Producto, Marca, Lugar
from typing import List

class ProductosOut(ModelSchema):
    class Config:
        model = Producto
        model_fields = ['id', 'codigo', 'lugar', 'marca', 'cantidad_disponible', 'precio_unitario', 'medidas']

class MarcaOut(ModelSchema):
    class Config:
        model = Marca
        model_fields = ['id', 'nombre', 'descripcion']


class LugarOut(ModelSchema):
    class Config:
        model = Lugar
        model_fields = ['id', 'nombre', 'descripcion']


api = NinjaAPI()

@api.get("/productos", response=List[ProductosOut])
def get_all_products(request):
    qs = Producto.objects.all()
    return qs

@api.get("/lugares", response=List[LugarOut])
def get_all_places(request):
    qs = Lugar.objects.all()
    return qs

@api.get("/marcas", response=List[MarcaOut])
def get_all_brands(request):
    qs = Marca.objects.all()
    return qs



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('productos/', include('productos.urls')),
    path('ventas/', include('ventas.urls')),
    path('compras/', include('compras.urls')),
    path("api/", api.urls),
    path('', RedirectView.as_view(pattern_name='producto-list'), name='index'),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

compras/models.py
from django.db import models
from django.contrib.auth.models import User
from productos.models import Producto


class Proveedor(models.Model):
    nombre = models.CharField(max_length=255, verbose_name='Nombre')
    direccion = models.TextField(verbose_name='Dirección')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'


class Compra(models.Model):
    usuario = models.ForeignKey(
        User, related_name='compras', on_delete=models.CASCADE)
    proveedor = models.ForeignKey(
        Proveedor, related_name='compras', on_delete=models.CASCADE)
    fecha_emision = models.DateTimeField(
        auto_now_add=True, verbose_name='Fecha Emisión')
    productos = models.ManyToManyField(
        Producto, related_name='compras', through='DetalleCompra')

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = 'Compra'
        verbose_name_plural = 'Compras'


class DetalleCompra(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(verbose_name='Cantidad')
    precio_unitario_compra = models.DecimalField(
        max_digits=9, decimal_places=2, verbose_name='Precio Unitario Compra')
    precio_unitario_venta = models.DecimalField(
        max_digits=9, decimal_places=2, verbose_name='Precio Unitario Venta')

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = 'Detalle de Compra'
        verbose_name_plural = 'Detalle de Compras'

compras/forms.py
from django import forms
from .models import Compra


class ProductoSelectForm(forms.Form):
    cantidad = forms.IntegerField(
        required=True,
        min_value=0,
        label='Cantidad',
        widget=forms.NumberInput(
            attrs={'placeholder': 'Cantidad'}
        )
    )
    precio_compra = forms.DecimalField(
        required=True,
        max_digits=9,
        min_value=0,
        decimal_places=2,
        label='Precio Compra',
        widget=forms.NumberInput(
            attrs={'placeholder': 'P. Compra'}
        )
    )
    precio_venta = forms.DecimalField(
        required=True,
        max_digits=9,
        min_value=0,
        decimal_places=2,
        label='Precio Venta',
        widget=forms.NumberInput(
            attrs={'placeholder': 'P. Venta'}
        )
    )


class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['proveedor']

compras/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotAllowed
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from compras.carrito import CarritoCompra
from productos.models import Producto
from .models import Proveedor, DetalleCompra
from .forms import ProductoSelectForm, CompraForm


@login_required
def compras(request):
    form_producto = ProductoSelectForm()
    form_compra = CompraForm()
    word = request.GET.get('word', '')
    productos = Producto.objects.filter(
        Q(codigo__icontains=word) | Q(medidas__icontains=word) |
        Q(marca__nombre__icontains=word)).all()
    context = {
        'productos': productos,
        'form_producto': form_producto,
        'form_compra': form_compra
    }
    return render(request, 'compras/compras.html', context)


class ProveedorListView(LoginRequiredMixin, ListView):
    # login required mixin
    login_url = reverse_lazy('login')
    # ListView section
    model = Proveedor

    def get_queryset(self):
        word = self.request.GET.get('word', '')
        proveedores = Proveedor.objects.filter(
            Q(nombre__icontains=word) | Q(direccion__icontains=word))
        return proveedores


class ProveedorCreateView(LoginRequiredMixin, CreateView):
    # login required mixin
    login_url = reverse_lazy('login')
    # view section
    model = Proveedor
    fields = ['nombre', 'direccion']
    success_url = reverse_lazy('proveedor-list')


class ProveedorUpdateView(LoginRequiredMixin, UpdateView):
    # login required mixin
    login_url = reverse_lazy('login')
    # view section
    model = Proveedor
    fields = ['nombre', 'direccion']
    success_url = reverse_lazy('proveedor-list')


class ProveedorDeleteView(LoginRequiredMixin, DeleteView):
    # login required mixin
    login_url = reverse_lazy('login')
    # view section
    model = Proveedor
    success_url = reverse_lazy('proveedor-list')


@login_required
def agregar_producto(request, pk):
    if request.method == 'POST':
        form = ProductoSelectForm(request.POST)
        if form.is_valid():
            cantidad = form.cleaned_data.get('cantidad', None)
            precio_compra = form.cleaned_data.get('precio_compra', None)
            precio_venta = form.cleaned_data.get('precio_venta', None)
            carrito = CarritoCompra(request)
            producto = Producto.objects.get(pk=pk)
            carrito.agregar(producto, cantidad, precio_compra, precio_venta)
            return redirect(reverse_lazy('compras'))
    return HttpResponseNotAllowed(['GET', 'PUT', 'DELETE'])


@login_required
def eliminar_producto(request, pk):
    carrito = CarritoCompra(request)
    producto = Producto.objects.get(pk=pk)
    carrito.eliminar(producto)
    return redirect(reverse_lazy('compras'))


@login_required
def limpiar_carrito(request):
    carrito = CarritoCompra(request)
    carrito.limpiar()
    return redirect(reverse_lazy('compras'))


@login_required
def guardar_compra(request):
    if request.method == 'POST':
        form = CompraForm(request.POST)
        if form.is_valid():
            compra = form.save(commit=False)
            compra.usuario = request.user
            compra.save()
            carrito = CarritoCompra(request)
            for key, value in carrito.carrito.items():
                producto_id = value.get('producto_id')
                cantidad = value.get('cantidad')
                precio_compra = value.get('precio_compra')
                precio_venta = value.get('precio_venta')
                DetalleCompra.objects.create(
                    compra=compra,
                    producto_id=producto_id,
                    cantidad=cantidad,
                    precio_unitario_compra=precio_compra,
                    precio_unitario_venta=precio_venta
                )
                producto = Producto.objects.get(pk=producto_id)
                producto.cantidad_disponible += cantidad
                producto.precio_unitario = precio_venta
                producto.save()
            carrito.limpiar()
            return redirect(reverse_lazy('compras'))
    return HttpResponseNotAllowed(['GET', 'PUT', 'DELETE'])

compras/templates/compras/carrito.html
{% load formclss %}

<div class="table-section">
    <form action="{% url 'compras-save' %}" method="POST">{% csrf_token %}
        <h4 class="mx-2 mt-2">Registrar Compra</h4>
        <div class="p-2 mb-3">
            {{ form_compra.proveedor|addclss:"form-control form-control-sm" }}
        </div>
        <table class="table table-borderless table-sm table-fixed">
            <thead>
            <tr class="text-center border-bottom">
                <th scope="col">
                    <small>Codigo</small>
                </th>
                <th scope="col">
                    <small>Cantidad</small>
                </th>
                <th scope="col">
                    <small>Precio Compra</small>
                </th>
                <th scope="col">
                    <small>Precio Venta</small>
                </th>
                <th scope="col">
                    <small>Subtotal</small>
                </th>
            </tr>
            </thead>
            <tbody>
            {% if request.session.carrito_compra.items %}
                {% for key, value in request.session.carrito_compra.items %}
                    <tr class="text-center">
                        <td style="max-width: 200px;">
                            <small>{{ value.codigo }}</small>
                        </td>
                        <td>
                            <small>{{ value.cantidad }}</small>
                        </td>
                        <td>
                            <small>{{ value.precio_compra }}</small>
                        </td>
                        <td>
                            <small>{{ value.precio_venta }}</small>
                        </td>
                        <td>
                            <small>{{ value.acumulado }} Bs</small>
                        </td>
                        <td>
                            <a href="{% url 'compras-del-producto' value.producto_id %}"
                               class="btn btn-danger btn-sm text-white text-center">x</a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr class="text-center">
                    <td colspan="6">Sin productos</td>
                </tr>
            {% endif %}
            <tr class="border-top">
                <th scope="row" class="text-center">
                    <small>Total:</small>
                </th>
                <td colspan="3"></td>
                <td class="text-center">
                    <small>{{ total_carrito_compra }} Bs</small>
                </td>
            </tr>
            </tbody>
        </table>
        {% if request.session.carrito_compra.items %}
            <div class="d-flex flex-row gap-2 p-2 border-top">
                <a href="{% url 'compras-clean' %}" class="btn btn-danger btn-sm flex-fill">Limpiar</a>
                <button type="submit" class="btn btn-primary btn-sm flex-fill">Registrar</button>
            </div>
        {% endif %}
    </form>
</div>

compras/templates/compras/compras.html
{% extends 'core/panel.html' %}
{% load formclss %}

{% block title %}Compras{% endblock %}

{% block content-panel %}
    <div class="py-4">
        <div class="row">
            <div class="col-7">
                <h4>Lista de productos</h4>
                <form class="d-flex flex-row justify-content-end gap-2 mb-3" action="." method="GET">
                    <input type="text" name="word" placeholder="Buscar" class="form-control"
                           value="{{ request.GET.word }}">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </form>
                <div class="table-section-modal">
                    <table class="table table-bordered table-sm table-fixed">
                        <thead>
                        <tr class="text-center border-bottom">
                            <th scope="col">Codigo</th>
                            <th scope="col">Stock</th>
                            <th scope="col">Medidas</th>
                            <th scope="col">Cantidad/P.Compra/P.Venta</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if productos %}
                            {% for producto in productos %}
                                <tr class="text-center">
                                    <td style="max-width: 200px;">
                                        <small>{{ producto.codigo }}</small>
                                    </td>
                                    <td>
                                        <small>{{ producto.cantidad_disponible }}</small>
                                    </td>
                                    <td>
                                        <small>{{ producto.medidas }}</small>
                                    </td>
                                    <td style="max-width: 300px;">
                                        <form class="d-flex gap-2 justify-content-center"
                                              action="{% url 'compras-add-producto' producto.id %}"
                                              method="post">{% csrf_token %}
                                            <div class="col-3">
                                                {{ form_producto.cantidad|addclss:"form-control form-control-sm" }}
                                            </div>
                                            <div class="col-3">
                                                {{ form_producto.precio_compra|addclss:"form-control form-control-sm" }}
                                            </div>
                                            <div class="col-3">
                                                {{ form_producto.precio_venta|addclss:"form-control form-control-sm" }}
                                            </div>
                                            <button class="col-1 btn btn-success btn-sm text-white">+</button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr class="text-center">
                                <td colspan="7">Sin datos disponibles</td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-5">
                <div class="border">
                    {% include 'compras/carrito.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

compras/templates/compras/proveedor_confirm_delete.html
{% extends 'core/panel.html' %}

{% block title %}Borrar proveedor {{ object.id }} {% endblock %}

{% block content-panel %}
    <div class="py-2 px-4 row">
        <form class="col-5 mt-5" method="POST">{% csrf_token %}
            <p class="fs-4">¿Esta seguro que desea eliminar el proveedor "{{ object }}"?</p>
            {{ form }}
            <div class="d-flex flex-row gap-2">
                <a href="{% url 'proveedor-list' %}" class="btn btn-secondary flex-fill">Cancelar</a>
                <button type="submit" class="btn btn-danger flex-fill">
                    Si, Eliminar
                </button>
            </div>
        </form>
    </div>
{% endblock %}

compras/templates/compras/proveedor_form.html
{% extends 'core/panel.html' %}
{% load formclss %}

{% block title %}{% if object %}Editar{% else %}crear{% endif %} proveedor{% endblock %}

{% block content-panel %}
    <div class="row py-2 px-4">
        <div class="card col-5 mx-auto">
            <div class="card-body">
                <div class="card-title">
                    <h3>{% if object %}Editar{% else %}Crear{% endif %} Proveedor</h3>
                </div>
                <form action="." method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_nombre" class="form-label">{{ form.nombre.label }}</label>
                        {{ form.nombre|addclss:"form-control" }}
                    </div>
                    <div class="mb-3">
                        <label for="id_direccion" class="form-label">{{ form.direccion.label }}</label>
                        {{ form.direccion|addclss:"form-control" }}
                    </div>
                    <div class="d-flex flex-row gap-2">
                        {% if object %}
                            <a href="{% url 'proveedor-delete' object.id %}"
                               class="btn flex-fill btn-danger">Eliminar</a>
                        {% endif %}
                        <a href="{% url 'proveedor-list' %}" class="btn flex-fill btn-secondary">Cancelar</a>
                        <button type="submit" class="btn flex-fill btn-primary">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

compras/templates/compras/proveedor_list.html
{% extends 'core/panel.html' %}

{% block title %}Proveedores{% endblock %}

{% block content-panel %}
    <div class="py-4">
        <div class="d-flex flex-row justify-content-between mb-4">
            <a href="{% url 'proveedor-create' %}" class="btn btn-primary">
                Nuevo
            </a>
            <form class="d-flex flex-row gap-2" action="." method="GET">
                <input type="text" name="word" class="form-control flex-fill" value="{{ request.GET.word }}"
                       placeholder="Buscar proveedores">
                <button class="btn btn-success" type="submit">Buscar</button>
            </form>
        </div>
        <div class="table-section border">
            <table class="table table-borderless table-sm table-fixed">
                <thead>
                <tr class="text-center border-bottom">
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Dirección</th>
                    <th scope="col">Acciones</th>
                </tr>
                </thead>
                <tbody>
                {% if object_list %}
                    {% for proveedor in object_list %}
                        <tr class="text-center">
                            <td>{{ proveedor.id }}</td>
                            <td>{{ proveedor.nombre }}</td>
                            <td>{{ proveedor.direccion }}</td>
                            <td>
                                <a href="{% url 'proveedor-update' proveedor.pk %}" class="btn btn-success btn-sm">Editar</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr class="text-center">
                        <td colspan="7">Sin datos disponibles</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}